version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: appuser
      MONGO_INITDB_ROOT_PASSWORD: appuserpass
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
