org: ljimen1
app: services
service: services
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  useDotenv: true

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-esbuild
  - serverless-offline
